## https://github.com/marketplace/actions/telegram-message-action
name: Send Telegram Message

on:
  workflow_call:
    inputs:
      token:
        description: 'Telegram Bot Token'
        required: true
      chat_id:
        description: 'Telegram Chat ID'
        required: true

jobs:
  telegram_message:
    runs-on: ubuntu-latest
    name: Send Telegram Message
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Send Inline Telegram Message
        uses: cbrgm/telegram-github-action@v1.0.9
        with:
          to: ${{ inputs.chat_id }}
          token: ${{ inputs.token }}
          message: |
            ğŸš€ **New commit by ${{ github.actor }}!**

            **Commit:** ${{ github.event.head_commit.message }}
            **Repository:** ${{ github.repository }}
            **View changes:** [GitHub Commit](${{ github.event.head_commit.url }})

            ğŸ“ **Commit Details:**
            - Author: ${{ github.event.head_commit.author.name }}
            - Email: ${{ github.event.head_commit.author.email }}
            - Date: ${{ github.event.head_commit.timestamp }}

            ğŸŒ **Repository Details:**
            - Branch: ${{ github.ref }}
            - SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})